projects/ViewCustom/ViewCustom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

handler404 = 'app.views.page_not_found'
handler500 = 'app.views.server_error'

projects/ViewCustom/app/urls.py
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from .models import Game
from . import views

app_name = 'app'
urlpatterns = [
    path('function/', include([
        path('', views.index, name='index'),
        path('test', views.test, name='test'),
        path('<int:pk>/', views.detail, name='detail'),
        path('post_only', views.post_only, name='post_only'),
    ])),

    path('class_base/', include([
        path('normal_view', csrf_exempt(views.NormalView.as_view())),
        path('template_view', csrf_exempt(views.TempVi.as_view())),
        path('redirect_view', views.ReVi.as_view()),
    ])),

    path('class_display/', include([
        path('detail_view/<int:pk>', views.DeVi.as_view(), name='detail_view'),
        path('list_view', views.LiVi.as_view(), name='list_view'),
    ])),

    path('class_edit/', include([
        path('form_view', csrf_exempt(views.FormVi.as_view()), name='form_view'),
        path('create_view', csrf_exempt(views.CreateVi.as_view()), name='create_view'),
        path('update_view/<int:pk>', csrf_exempt(views.UpdateVi.as_view()), name='update_view'),
        path('delete_view/<int:pk>', csrf_exempt(views.DeleteVi.as_view()), name='delete_view'),
    ])),

    path('class_date/', include([
        path('archive_view',
             views. ArchiveIndexVi.as_view(model=Game, date_field="release", template_name="archive_vi.html"),
             name="archive_view"),
        path('year_archive_view/<int:year>', views.YearArchiveVi.as_view(), name="year_archive_view"),
    ])),

    path('advanced/', include([
        path('csv_python', views.csv_render_python_library, name='csv_python'),
        path('csv_template', views.csv_render_template, name='csv_template'),
        path('pdf_render', views.pdf_render, name='pdf_render'),
    ])),
]

projects/ViewCustom/app/templates/archive_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> Archive Index View</h1>
    <ul>
    {% for game in latest %}
        <li>{{ game.release }}: {{ game }}</li>
    {% endfor %}
</ul>
</body>
</html>

projects/ViewCustom/app/templates/create_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Create View</h1>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

projects/ViewCustom/app/templates/de_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Detail view</h1>
    <h4>{{ object.name }} - {{ object.man.name }}</h4>
    <h5>{{ object.release}}</h5>
    <h6>{{ hihi }}</h6>
</body>
</html>

projects/ViewCustom/app/templates/delete_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Delete View</h1>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</form>
</body>
</html>

projects/ViewCustom/app/templates/form_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Form View</h1>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Buy">
</form>
</body>
</html>

projects/ViewCustom/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ol>
        <li><a href="{% url 'app:detail_view' pk=game_num %}" target="_blank">Detail View</a></li>
        <li><a href="{% url 'app:list_view' %}" target="_blank">List View</a></li>
        <li><a href="{% url 'app:form_view' %}" target="_blank">Form View</a></li>
        <li><a href="{% url 'app:create_view' %}" target="_blank">Create View</a></li>
        <li><a href="{% url 'app:update_view' pk=man_num %}" target="_blank">Update View</a></li>
        <li><a href="{% url 'app:delete_view' pk=man_num %}" target="_blank">Delete View</a></li>
        <li><a href="{% url 'app:archive_view' %}" target="_blank">Archive View</a></li>
        <li><a href="{% url 'app:year_archive_view' year=2019 %}" target="_blank">Year Archive View</a></li>
    </ol>
<script style="text/javascript" src="{% static 'app/test.js'%}"></script>
</body>
</html>

projects/ViewCustom/app/templates/li_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>List view</h1>
    {% for object in object_list %}
    <h4>{{ object.name }} - {{ object.man.name }}</h4>
    {% endfor %}
    <h6>{{ hihi }}</h6>
</body>
</html>

projects/ViewCustom/app/templates/normal_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Normal view</h1>
    {{ hahaha }}
</body>
</html>

projects/ViewCustom/app/templates/temp_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Template view</h1>
    {{ hihi }}
    {% csrf_token %}
</body>
</html>

projects/ViewCustom/app/templates/update_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Update View</h1>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
</body>
</html>

projects/ViewCustom/app/templates/year_archive_vi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Year Archive View</h1>
    <ul>
        {% for date in date_list %}
            <li>{{ date|date }}</li>
        {% endfor %}
    </ul>

    <div>
        <h1>All Games for {{ year|date:"Y" }}</h1>
        {% for obj in object_list %}
            <p>
                {{ obj }} - {{ obj.release|date:"F j, Y" }}
            </p>
        {% endfor %}
    </div>
</body>
</html>